### ISSUE TITLE
[FIX] 게시판 서비스 전체 수정 및 리팩토링

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#123]
## 📕 제목
 - 게시판 서비스 전체 수정 및 리팩토링
## 📔 설명
 - 게시판 서비스의 전반적인 수정이 필요합니다. 제가 전반적으로 수정을 하긴 했는데, 추가적으로 수정해야할 부분에 대해서 To-do에 작성해서 드리겠습니다. 
## 🏫 To-do
- [x] Comment 서비스의 return 값이 전부 boardResponse입니다 -> 필요에 따라 알맞는 Response를 생성해주세요. Domain만 반환해도 된다면 일단 Domain만 반환해도 괜찮습니다. 
- [x] Service를 호출하는 parameter에 request를 넣어줍시다. 개별적인 값들을 전부 다 넣는것은 불필요합니다 - > service 전체를 통일해주세요
- [x] Service에서 게시글, 댓글을 삭제하거나 수정하는 작업을 할떄 userId가 일치하는지 확인하는 작업이 필요합니다. - > service 전체를 확인하면서 추가해주세요. 제가 일부분 추가하긴했습니다. 
- [x] 전부 다 수정후에, Notion Api 명세서에 update해주세요. 이미 작성이 되어 있는데 수정된 부분이 있으면, 수정해서 추가해주세요

**Comment by hyojaeKwon** [comment]
@JunHyungJang 
userId일치하는지 확인하는 작업은 domain과 관련된 로직이라 domain안에서 이뤄져야 할 것 같습니다. 어떡해 생각하시나요?

**Comment by JunHyungJang** [comment]
> @JunHyungJang userId일치하는지 확인하는 작업은 domain과 관련된 로직이라 domain안에서 이뤄져야 할 것 같습니다. 어떡해 생각하시나요?
네 맞는거 같습니다
