### ISSUE TITLE
[FEAT] API-gateway와 인증서버 통합로직 확인하기 

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#144]
## 📕 제목
- API-gateway와 인증서버 통합로직 확인하기 
## 📔 설명
- api-gateway의 filter부분을 제가 핸들링하려고 했는데, 인증로직과 관련된게 너무 많아서 효재님께 넘깁니다.
- 현재 테스트를 위해 AccessToken은 유효기간이 10초입니다.  
- api-gateway, eureka-server, user-service를 동시에 실행시킨후에 http://localhost:9014/user-service/api/health 해당 url로 접속하면 직접 user-service에 접근하는것이 아닌 gateway를 거쳐서 접근가능합니다. 
- "POSTMAN"을 통해서 접속이 잘되는지 확인해주세요
- To-do에 구현할 내용들 남기겠습니다. 
## 🏫 To-do
- [ ] refreshToken invalid
- AccessToken이 만료된 후에 refreshToken을 확인해야하는 부분에서 refreshToken invalid 에러가 발생합니다. 
- [ ] user-service 잘못된 url에서 토큰발급
- 현재 Login에서만 accesstoken과 refreshtoken이 발급되어야 하는데 다른 url에서도 토큰이 발급됩니다 
- [ ] user-service 호출시 토큰 자동삭제
- 이유를 모르겠지만, api-gateway를 거쳐서 healthcheck 를 실행하면 token값이 사라집니다. 확인 부탁드립니다. 
- [ ] secret key 공유방법
- 같이 고민해야하는 부분이지만, api-gateway와 user-service다 공통의 secretkey를 공유합니다. 어떻게 두 서비스가 같은 키를 공유할지 생각해보세요 
- [ ] api-gateway 테스트 필요
- user-service의 모든 url들이 깔끔하게 게이트웨이를 거쳐서 호출되는지 확인해야 합니다. 확인후에 api 명세서에 기록 부탁드립니다.

**Comment by hyojaeKwon** [comment]
준형님 정리 감사합니다. 하나씩 차근차근 풀어가보겠습니다.
