### ISSUE TITLE
[FEAT] Board, User, Chat service gateway에 연결하기

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#152]
## 📕 제목
Board, User, Chat service gateway에 연결하기
## 📔 설명
Board, User, Chat service를 spring eureka server에 연결하고, cloud gateway에서 사용자 정보 인증받기

## 🏫 To-do
- [x] service eureka client로 등록하기
- [x] api gateway에서 Auth filter연결하기
- [x] 각 서비스 health 확인하기
