### ISSUE TITLE
[FEAT] 채팅서버 서버 로직 추가 

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#24]
## 📕 제목
채팅서버내에 여러 로직 및 기능들 추가 
## 📔 설명
추가적인 테스트와 구현을 위한 이슈발행
## 🏫 To-do
- [ ] Controller Test 추가
- [ ] 도메인 Test 추가 
- [ ] 도메인 로직 추가
