### ISSUE TITLE
[FEAT] 채팅방 서비스 소형 테스트 코드 작성

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#41]
## 📕 제목
채팅방 서비스 소형 테스트 코드 작성
## 📔 설명
Domain, Service, Controller 에 대한 유닛테스트 작성
## 🏫 To-do
- [ ] Domain 소형 테스트코드
- [ ] Service 소형 테스트코드
- [ ] Controller 소형 테스트 코드 작성
