### ISSUE TITLE
[FEAT] 유저 서버 통일된 exception 적용하기

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#52]
## 📕 제목
유저 서버 통일된 exception 적용하기
## 📔 설명
기존 사용했던 예외 처리 방법을 수정합니다.

1. 유저 서버의 통일된 exception을 적용합니다.
2. service layer의 수행 결과를 사용자에게 전달합니다.
3. custom exception handler를 구현하여 적용합니다.

## 🏫 To-do
- [ ] enum으로 예외 상황 정리하기
- [ ] response template 제작하기
- [ ] custom exception handler 적용하기
