### ISSUE TITLE
[FEAT] 서비스, 도메인 test code 구현하기

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#59]
## 📕 제목
서비스, 도메인, 컨트롤러 test code 구현하기

## 📔 설명
- 지금까지 만들어진 domain, service, controller 에 대해 test를 진행합니다. 

## 🏫 To-do
- [x] User 도메인에 대한 생성, 수정 test 수행하기
- [ ] UserCreateService, UserService test 수행하기
- [ ] UserController, UserCreateController test수행하기
