### ISSUE TITLE
[FEAT] User 회원 인증 service test 구현하기

### ISSUE THREAD

**Issue by hyojaeKwon** [connetist/connectist-backend#62]
## 📕 제목
user 인증 service test 구현하기

## 📔 설명
- 사용자가 이메일 및 학교를 인증받기 위해 거치는 user service의 test를 구현합니다.
- 이를 위한 domain test까지 병행합니다.

## 🏫 To-do
- [x] fake certification 구현
- [x] domain test 구현
- [x] service test 구현
